# This configuration file is for the **development** setup.
version: '3.2'
# For a production example please refer to getredash/setup repository on GitHub.
services:
  server:
    build: .
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - ".:/app"
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_RATELIMIT_ENABLED: "false"
      REDASH_MAIL_DEFAULT_SENDER: "Rajesh.Korandla@hexstream.com"
      REDASH_MAIL_SERVER: "in-v3.mailjet.com"
      REDASH_MAIL_PORT: 587
      REDASH_MAIL_USERNAME: "e7b48acd596f0f32ec81e0127d95acc0"
      REDASH_MAIL_PASSWORD: "fc701ff3fe133f6ed831133d6449c0a1"
      REDASH_SERVER: "server"

  scheduler:
    build: .
    command: dev_scheduler
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_MAIL_DEFAULT_SENDER: "Rajesh.Korandla@hexstream.com"
      REDASH_MAIL_SERVER: "in-v3.mailjet.com"
      REDASH_MAIL_PORT: 587
      REDASH_MAIL_USERNAME: "e7b48acd596f0f32ec81e0127d95acc0"
      REDASH_MAIL_PASSWORD: "fc701ff3fe133f6ed831133d6449c0a1"
      REDASH_SERVER: "server"
  worker:
    build: .
    command: dev_worker
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_MAIL_DEFAULT_SENDER: "Rajesh.Korandla@hexstream.com"
      REDASH_MAIL_SERVER: "in-v3.mailjet.com"
      REDASH_MAIL_PORT: 587
      REDASH_MAIL_USERNAME: "e7b48acd596f0f32ec81e0127d95acc0"
      REDASH_MAIL_PASSWORD: "fc701ff3fe133f6ed831133d6449c0a1"
      REDASH_SERVER: "server"
  redis:
    image: redis:3-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    ports:
      - "15432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  email:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    restart: unless-stopped
